name: Build & Deploy to Azure App Service

on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Frontend (React / Vite) ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install & build client
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Copy client dist to server/wwwroot
        run: |
          rm -rf server/wwwroot
          mkdir -p server/wwwroot
          cp -r client/dist/* server/wwwroot/

      # ---------- Backend (.NET 8) ----------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        working-directory: server
        run: dotnet restore

      - name: Build
        working-directory: server
        run: dotnet build -c Release --no-restore

      # (Optional) run tests if you add them
      # - name: Test
      #   run: dotnet test -c Release --no-build --verbosity normal

      - name: Publish
        working-directory: server
        run: dotnet publish -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: server/publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
            package: ./publish
